export const cursosDisponibles = [
    {id: 1, nombre: "Canva", precio: 29.99 , cargaHoraria: 20, imgclass:"imagenCursoDestacadoIndex" , imgsrc:"../images/Curso canva.png", imgalt:"Curso Canva" , titulo: "Curso completo de Canva" , filtro: "diseño"},
    {id: 2, nombre: "Blenderdiseño3d", precio: 69.99, cargaHoraria: 50 , imgclass:"imagenCursoDestacadoIndex" , imgsrc:"../images/Curso blender diseño 3d.png", imgalt:"Curso Blender" , titulo: "Curso de Blender - Diseño 3D" , filtro: "diseño"},
    {id: 3, nombre: "JavaScript", precio: 59.99 , cargaHoraria: 60 , imgclass:"imagenCursoDestacadoIndex" , imgsrc:"../images/Curso javascript.png", imgalt:"Curso JavaScript" , titulo: "Curso completo de JavaScript" , filtro : "programacion"},
    {id: 4, nombre: "Python", precio: 59.99 , cargaHoraria: 62 , imgclass:"imagenCursoDestacadoIndex" , imgsrc:"../images/Curso python.png", imgalt:"Curso Python" , titulo: "Curso completo de Python" , filtro : "programacion"},
    {id: 5, nombre: "Chat Gpt", precio: 49.99 , cargaHoraria: 50 , imgclass:"imagenCursoDestacadoIndex" , imgsrc:"../images/Curso chat gpt.png", imgalt:"Curso ChatGPT" , titulo: "Curso completo de ChatGPT" , filtro : "inteligencia artificial"},
    {id: 6, nombre: "Illustrator", precio: 49.99 , cargaHoraria: 40 , imgclass:"imagenCursoDestacadoIndex" , imgsrc:"../images/Curso illustrator.png", imgalt:"Curso Illustrator" , titulo: "Curso completo de Illustrator" , filtro: "diseño"},
    {id: 7, nombre: "Photoshop", precio: 39.99, cargaHoraria: 32 , imgclass:"imagenCursoDestacadoIndex" , imgsrc:"../images/Curso photoshop.png", imgalt:"Curso Photoshop" , titulo: "Curso completo de Photoshop" , filtro: "diseño"},
    {id: 8, nombre: "Java", precio: 59.99, cargaHoraria: 62 , imgclass:"imagenCursoDestacadoIndex" , imgsrc:"../images/Curso java.png", imgalt:"Curso Java" , titulo: "Curso completo de Java" , filtro : "programacion"},
    {id: 9, nombre: "Programacion C", precio: 49.99 , cargaHoraria: 50 , imgclass:"imagenCursoDestacadoIndex" , imgsrc:"../images/Curso programacion c.png", imgalt:"Curso C" , titulo: "Curso de Programación en C" , filtro : "programacion"},
    {id: 10, nombre: "Inteligencia artificial (AI)", precio: 69.99 , cargaHoraria: 55 , imgclass:"imagenCursoDestacadoIndex" , imgsrc:"../images/Curso inteligencia artificial.png", imgalt:"Curso AI" , titulo: "Curso de Inteligencia Artificial" , filtro : "inteligencia artificial"},
    {id: 11, nombre: "AI: Generación de Prompts", precio: 39.99 , cargaHoraria: 25 , imgclass:"imagenCursoDestacadoIndex" , imgsrc:"../images/Curso generacion de prompts.png", imgalt:"Curso AI Prompts" , titulo: "Curso de Generación de Prompts con IA" , filtro : "inteligencia artificial"},
    {id: 12, nombre: "AI: Marketing Digital", precio: 59.99 , cargaHoraria: 45 , imgclass:"imagenCursoDestacadoIndex" , imgsrc:"../images/Curso marketing digital AI.png", imgalt:"Curso AI Marketing" , titulo: "Curso de Marketing Digital con IA" , filtro : "marketing"},
]